/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aEUdOsD6Wz6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

export default function ChatBot() {
  return (
    <Card className="w-full max-w-sm mx-auto">
      <CardHeader className="rounded-t-lg">
        <CardTitle className="text-center">Chat</CardTitle>
        <CardDescription className="text-center">
          Talk to our automated assistant
        </CardDescription>
      </CardHeader>
      <CardContent className="p-0">
        <div className="grid gap-2 p-4">
          <div className="rounded-lg bg-gray-100 dark:bg-gray-800 p-4 text-sm">
            Hi there! How can I help you today?
          </div>
          <div className="rounded-lg bg-gray-100 dark:bg-gray-800 p-4 text-sm self-end">
            I'm having trouble signing in. Can you help me?
          </div>
          <div className="rounded-lg bg-gray-100 dark:bg-gray-800 p-4 text-sm">
            Of course! First, can you tell me what error message you're seeing?
          </div>
        </div>
        <div className="border-t border-gray-200 dark:border-gray-700">
          <div className="flex items-center space-x-2 p-2">
            <Input
              className="flex-1 min-w-0 border-0 shadow-none"
              placeholder="Type a message..."
            />
            <Button size="sm">Send</Button>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
